# This Makefile works for only MSVC and Windows
# Ran this with "nmake" like this: nmake /f Makefile.win

CC=cl
CFLAGS=/std:c11 /experimental:c11atomics /W4 /Fo:build\ /DLOGGER_IMPLEMENTATION /DLOGGER_BUILD /D_CRT_SECURE_NO_WARNINGS /D_REENTRANT

BUILD = build
HEADER = logger.h
DLL = $(BUILD)\logger.dll

!IF "$(debug)"=="1"
CFLAGS=$(CFLAGS) /DLOGGER_DEBUG /Zi /Od /LDd /MDd
!ELSE
CFLAGS=$(CFLAGS) /O2 /MD /LD
!ENDIF

all: $(DLL) $(NOIMPL_HEADER)

$(BUILD):
	if not exist $(BUILD) mkdir $(BUILD)

$(DLL): $(HEADER) $(BUILD)
	$(CC) $(CFLAGS) /Fe:$(DLL) /TC $(HEADER)

clean:
	rmdir /S /Q $(BUILD)

.PHONY: all clean
